In [2]:
import numpy as np

In [146]:
#1 D array isko vector kehte hai
a = np.array([i for i in range(1,10)])
print(a)

[1 2 3 4 5 6 7 8 9]


In [4]:
# 2D array isko metrix kehte hai
a = np.array([[j for j in range(1, 10)] for i in range(1,10) ])
print(a)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [5]:
#3 D array isko hi tensor array kehte hai
a = np.array([[[n for n in range(1,10)] for j in range(1,4)] for i in range(1,4)])
print(a)

[[[1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]]

 [[1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]]

 [[1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]]]


In [6]:
# changing data type of array
a = np.array([i for i in range(1,10)], dtype=float)
b = np.array([i for i in range(1,10)], dtype=str)
c = np.array([i for i in range(1,10)], dtype=bool)
d = np.array([i for i in range(1,10)], dtype=complex)
print(a)
print(b)
print(c) #non zero element ko python True ki tarah treat karta hai
print(d)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
['1' '2' '3' '4' '5' '6' '7' '8' '9']
[ True  True  True  True  True  True  True  True  True]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]


In [7]:
# np.arange
a = np.arange(1, 11, 2)
print(a)

[1 3 5 7 9]


In [8]:
#.reshape(row's, column's) you can reshape array when range == row's X column's
np.arange(1,13).reshape(2 , 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
# np.zeros(row, columns)  and  np.ones(row , columns)
a = np.ones((3,4))
print(a)
b = np.zeros((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#np.random.random((row's, column's))
np.random.random((3,4))

array([[0.34422184, 0.3800335 , 0.07133728, 0.73366838],
       [0.54035917, 0.89147748, 0.87898014, 0.21058141],
       [0.49320023, 0.38102682, 0.90531571, 0.08358116]])

In [11]:
#np.linspace(starting_idx, ending_idx, no_element's)
#ye do point's ke beech ke equal linear space ko print karega

np.linspace(-100, 100, 10)

array([-100.        ,  -77.77777778,  -55.55555556,  -33.33333333,
        -11.11111111,   11.11111111,   33.33333333,   55.55555556,
         77.77777778,  100.        ])

In [12]:
#np.identity(size) Ye function identity matrix ko generate karega
#identity matrix mtlab diagonal element 1 and remainig element 0 hote hai
#default values float hoti hai
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#Numpy Attribute's

In [14]:
a1 = np.arange(10, dtype=np.int32) #vector
a2 = np.arange(12, dtype=float).reshape(3,4) #matrix
a3 = np.arange(8).reshape(2,2,2) # tensor

print('1D ->', a1)
print('2D ->' , a2)
print('3D ->' , a3)

1D -> [0 1 2 3 4 5 6 7 8 9]
2D -> [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
3D -> [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [15]:
#ndim -> ye array ka dimention batata hai 1D, 2D, 3D, ND hai
print(a3.ndim)

3


In [16]:
#shape -> ye shape bata hai jaise row's and columns

print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [17]:
#size -> ye batata hai ki size kya hai array ki

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [18]:
# itemsize -> ye batata hai ki each item from array kitni size occupy kar raha hai memory me

a1.itemsize #size depend karta hai machine pe 64 bit machine pe 8 byte aur 32 bit machine pe 4 byte size dega integer ke liye


4

In [19]:
#dtype -> ye type batata hai int hai ya float ya other kuch
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [20]:
# changing Datatype

#astype

a2.astype(np.int16)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int16)

In [21]:
#Array Operation's
a2 = np.arange(12).reshape(3,4)
a1 = np.arange(12, 24).reshape(3,4)


In [22]:
#SCALER OPERATION
#arithmatic operation's
print("->", a1 + 1)
print("->", a1 - 1)
print("->", a1 * 1)
print("->", a1 ** 2)
print("->", a1 / 2)
print("->", a1 % 2)


-> [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
-> [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
-> [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
-> [[144 169 196 225]
 [256 289 324 361]
 [400 441 484 529]]
-> [[ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]
-> [[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [148]:
#Relational Operation's
print("->", a1 > 5) #iska matlab hai each element from a1 is greater the 5 or not
print("->", a1 ==1)
print("->", a1 < 5)
print("->", a1 != 0)
print("->", a1 >= 5)
print("->", a1 <= 5)

-> [[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
-> [[False  True False False]
 [False False False False]
 [False False False False]]
-> [[ True  True  True  True]
 [ True False False False]
 [False False False False]]
-> [[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
-> [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
-> [[ True  True  True  True]
 [ True  True False False]
 [False False False False]]


In [24]:
#Vector Operation's

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print("a1 ->  ", a1)
print("a2 ->  ", a2)


a1 ->   [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a2 ->   [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [25]:
print("->", a1 > a2)
print("->", a1 < a2)
print("->",a1 >= a2)
print("->", a1 <= a2)
print("->", a1 == a2)
print("->", a1 != a2)

-> [[False False False False]
 [False False False False]
 [False False False False]]
-> [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
-> [[False False False False]
 [False False False False]
 [False False False False]]
-> [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
-> [[False False False False]
 [False False False False]
 [False False False False]]
-> [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [26]:
#Array Function's

a1 = np.random.random((3,3))
print('A1 -> ', a1)
a1 = np.round(a1 * 100) #decimal ko nearest element me convert karta hai
print('nearest ->', a1)

A1 ->  [[0.42981335 0.98953475 0.09135302]
 [0.14032764 0.06134354 0.64206318]
 [0.95879339 0.86504777 0.27813921]]
nearest -> [[43. 99.  9.]
 [14.  6. 64.]
 [96. 87. 28.]]


In [27]:
#mathmatical function of array
#max / min / sum / prod / axis = 0 -> col and axit = 1 -> row's
print(np.max(a1, axis=0)) #max -> ye batata hai ki pure array me se max element kya hai
print(np.min(a1 , axis = 1)) #min element batata hai
print(np.sum(a1, axis = 0)) #pure array ka sum calculate karega
print(np.prod(a1, axis = 1)) #pure array ka product nika ke deta hai

[96. 99. 64.]
[ 9.  6. 28.]
[153. 192. 101.]
[ 38313.   5376. 233856.]


In [28]:
#some statistical operation's
#mean / median / standard deviation(std) / veriance(var)
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
print(np.mean(a1, axis = 1))
print(np.median(a1, axis = 0))
print(np.std(a1, axis= 1))
print(np.var(a1, axis = 0))

[1.5 5.5 9.5]
[4. 5. 6. 7.]
[1.11803399 1.11803399 1.11803399]
[10.66666667 10.66666667 10.66666667 10.66666667]


In [30]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
#Trignometric function
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]
[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257 ]]
[[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01]
 [ 1.15782128e+00 -3.38051501e+00 -2.91006191e-01  8.71447983e-01]
 [-6.79971146e+00 -4.52315659e-01  6.48360827e-01 -2.25950846e+02]]


In [33]:
#Dot Product (imp topic)
a1 = np.arange(12).reshape((3,4))
a2 = np.arange(12).reshape((4,3))
print(a1.dot(a2))

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


In [36]:
#log and exponents
print(np.log(a1))
print(np.exp(a2))

[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04]]


/tmp/ipython-input-4028056899.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))


In [51]:
#round / floor / cell
a3 = np.random.random((3,4)) * 100
print(np.round(a3))
print(np.floor(a3))
print(np.ceil(a3))

[[71.  8. 90. 45.]
 [ 7. 54.  2. 73.]
 [47. 40. 24. 73.]]
[[70.  7. 90. 44.]
 [ 6. 54.  1. 72.]
 [46. 39. 24. 73.]]
[[71.  8. 91. 45.]
 [ 7. 55.  2. 73.]
 [47. 40. 25. 74.]]


In [52]:
#indexing and Slicing
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
n = [i for i in range(1,10)]

In [74]:
#indexing hamesha 0 se start hoti hai
n #1D matrix

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [76]:
print(n[ 4])

5


In [63]:
a2 #2D matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
print(a2[2, 2])

8


In [66]:
# 3D matrix, tensor
a = np.array([[[n for n in range(1,10)] for j in range(1,4)] for i in range(1,4)])
a

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [69]:
print(a[1,0,4 ]) #iska matlab hua a ke 1 row ke 0 row aur 4 column pe ka element print kar do
print(a[0,0,0])

5
1


In [70]:
print(a[2, 2, 5])

6


In [77]:
#slicing
#1D
n

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [79]:
print(n[2:5])
print(n[::-1])

[3, 4, 5]
[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [102]:
#2D
m = a2.reshape((3,4))
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [106]:
print(m[0, :]) #0 ka matlab hua 0th row
print(m[:, 0]) #0 ka matlab hua 0th col
print(m[1:, 1:3])
print(m[::2, ::3])
print(m[::2, 1::2])
print(m[1, ::3])
print(m[:2, 1::])

[0 1 2 3]
[0 4 8]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [107]:
#3D matrix/tensor
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [115]:
print(a3[1, 1, ::])
print(a3[0, 1, ::])
print(a3[2, 2, 1])
print(a3[2, 1::, 1::])
print(a3[::2, 0, ::2])

[12 13 14]
[3 4 5]
25
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


In [117]:
#iteration
#1D
n
for i in n:
  print(i)

1
2
3
4
5
6
7
8
9


In [121]:
#2D
m
for i in m:
  print(i) #each row ko print karega


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [126]:
#3D
a3

for i in np.nditer(a3):
  print(i)

for i in a3:
  for j in i:
    for k in j:
      print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [130]:
#Reshaping

#transpose -> ye row ko col aur col ko row bana deta hai
m
print(np.transpose(m))
#dusra tarika
print(m.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [132]:
#ravel -> ye nD array ko 1D array me convert karta hai
m.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [136]:
#Stacking -> Ye n No of array's ko jod deta hai (bas sab ke row's and col's same home chahiye)
a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(3,4)
np.hstack((a3, a4)) #horizontal
np.vstack((a3, a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [137]:
a4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [142]:
np.hsplit(a4, 4)

[array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]]),
 array([[14],
        [18],
        [22]]),
 array([[15],
        [19],
        [23]])]

In [144]:
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
np.vsplit(a3, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]